name: 'DocSync AI'
description: 'AI-powered documentation sync agent that monitors PR merges and creates documentation update PRs when needed'
author: 'Deriv'

inputs:
  github_token:
    description: 'GitHub token with contents:write and pull-requests:write permissions'
    required: true
  anthropic_api_key:
    description: 'Anthropic API key for Claude AI'
    required: true
  slack_webhook_url:
    description: 'Slack webhook URL for notifications'
    required: false
    default: ''
  slack_users_to_tag:
    description: 'Comma-separated Slack user IDs to tag (e.g., U123ABC,U456DEF)'
    required: false
    default: ''
  repository:
    description: 'Repository name (owner/repo)'
    required: true
  commit_sha:
    description: 'Commit SHA that triggered this workflow'
    required: true
  base_branch:
    description: 'Base branch name (main or master)'
    required: false
    default: 'master'

outputs:
  pr_created:
    description: 'Whether a documentation PR was created (true/false)'
    value: ${{ steps.create-pr.outputs.pr_created }}
  pr_url:
    description: 'URL of the created PR (if any)'
    value: ${{ steps.create-pr.outputs.pr_url }}
  pr_number:
    description: 'Number of the created PR (if any)'
    value: ${{ steps.create-pr.outputs.pr_number }}
  files_updated:
    description: 'Documentation files that were updated'
    value: ${{ steps.create-pr.outputs.files_updated }}
  reasoning:
    description: "Claude AI's reasoning for the decision"
    value: ${{ steps.analyze.outputs.reasoning }}
  status:
    description: 'Overall status (success/skipped/error)'
    value: ${{ steps.finalize.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Setup and extract context
      id: setup
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
      run: |
        set -e
        
        echo "Configuring git..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        echo "Extracting PR information..."
        PR_INFO=$(gh pr list --search "$COMMIT_SHA" --state merged --json number,title,url --jq '.[0]' 2>/dev/null || echo '{}')
        
        PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number // "N/A"')
        PR_TITLE=$(echo "$PR_INFO" | jq -r '.title // "Direct commit"')
        PR_URL=$(echo "$PR_INFO" | jq -r '.url // "N/A"')
        
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT  
        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        
        echo "## DocSync AI Analysis" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Trigger:** PR #$PR_NUMBER - $PR_TITLE" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** \`$COMMIT_SHA\`" >> $GITHUB_STEP_SUMMARY

    - name: Gather repository context
      id: context
      shell: bash
      run: |
        set -e
        
        echo "Generating diff..."
        
        if git rev-parse --verify HEAD^2 2>/dev/null; then
          MERGE_BASE=$(git merge-base HEAD~1 HEAD)
          DIFF=$(git diff "$MERGE_BASE" HEAD 2>/dev/null || git diff HEAD~1 HEAD)
        else
          DIFF=$(git diff HEAD~1 HEAD 2>/dev/null || echo "")
        fi
        
        FILTERED_DIFF=$(echo "$DIFF" | grep -v -E "(package-lock|yarn\.lock|pnpm-lock|\.lock)" | head -n 4000)
        
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "")
        CHANGED_COUNT=$(echo "$CHANGED_FILES" | grep -c . || echo "0")
        
        echo "changed_count=$CHANGED_COUNT" >> $GITHUB_OUTPUT
        
        echo "$FILTERED_DIFF" > /tmp/diff.txt
        
        echo "Reading current documentation..."
        
        if [ -f "README.md" ]; then
          cat README.md > /tmp/readme.txt
          echo "readme_exists=true" >> $GITHUB_OUTPUT
        else
          echo "" > /tmp/readme.txt
          echo "readme_exists=false" >> $GITHUB_OUTPUT
        fi
        
        if [ -f "CLAUDE.md" ]; then
          cat CLAUDE.md > /tmp/claude_md.txt
          echo "claude_md_exists=true" >> $GITHUB_OUTPUT
        else
          echo "" > /tmp/claude_md.txt
          echo "claude_md_exists=false" >> $GITHUB_OUTPUT
        fi
        
        echo "Getting repository structure..."
        find . -type f \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.go" -o -name "*.java" -o -name "*.rs" -o -name "*.yml" -o -name "*.yaml" \) 2>/dev/null | grep -v node_modules | grep -v __pycache__ | grep -v .git | head -100 > /tmp/file_structure.txt || true
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Changed files:** $CHANGED_COUNT" >> $GITHUB_STEP_SUMMARY

    - name: Analyze changes with Claude AI
      id: analyze
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        REPOSITORY: ${{ inputs.repository }}
        PR_TITLE: ${{ steps.setup.outputs.pr_title }}
      run: |
        set -e
        
        echo "Analyzing with Claude AI..."
        
        DIFF_CONTENT=$(cat /tmp/diff.txt)
        README_CONTENT=$(cat /tmp/readme.txt)
        CLAUDE_MD_CONTENT=$(cat /tmp/claude_md.txt)
        FILE_STRUCTURE=$(cat /tmp/file_structure.txt)
        
        # Create system prompt file
        cat > /tmp/system_prompt.txt << 'SYSTEM_EOF'
        You are DocSync AI, an expert at analyzing code changes and determining if documentation needs to be updated.
        
        Your task is to analyze code changes and decide if README.md or CLAUDE.md need updates.
        
        CRITICAL RULES:
        1. ONLY update documentation files (README.md, CLAUDE.md) - never suggest changes to code files
        2. PRESERVE existing documentation structure and content - only modify sections that need updating
        3. Make MINIMAL, TARGETED changes - do not rewrite entire documents
        4. If no update is needed, clearly say so
        
        When to UPDATE documentation:
        - New features or functionality added
        - API changes (new endpoints, parameters, return values)
        - Configuration or setup changes
        - Usage pattern changes
        - New dependencies that users need to know about
        - Significant architectural changes
        
        When to SKIP documentation updates:
        - Bug fixes that do not change documented behavior
        - Internal refactoring with no external impact
        - Code style/formatting changes
        - Test file changes only
        - Minor performance optimizations
        SYSTEM_EOF
        
        # Create user prompt file
        cat > /tmp/user_prompt.txt << USER_EOF
        Repository: $REPOSITORY
        PR/Commit: $PR_TITLE
        
        ## Code Changes (Diff)
        \`\`\`diff
        $DIFF_CONTENT
        \`\`\`
        
        ## Repository File Structure
        \`\`\`
        $FILE_STRUCTURE
        \`\`\`
        
        ## Current README.md
        $(if [ -n "$README_CONTENT" ]; then echo '```markdown'; echo "$README_CONTENT"; echo '```'; else echo '(Does not exist)'; fi)
        
        ## Current CLAUDE.md
        $(if [ -n "$CLAUDE_MD_CONTENT" ]; then echo '```markdown'; echo "$CLAUDE_MD_CONTENT"; echo '```'; else echo '(Does not exist)'; fi)
        
        ## Instructions
        Analyze the code changes and determine:
        1. Does README.md need to be updated? If yes, provide the COMPLETE updated content.
        2. Does CLAUDE.md need to be updated? If yes, provide the COMPLETE updated content.
        
        IMPORTANT: 
        - Preserve existing content and structure
        - Only modify sections affected by the changes
        - Keep the same formatting style
        
        Respond with ONLY valid JSON (no markdown code blocks):
        {
          "update_readme": true/false,
          "update_claude_md": true/false,
          "readme_content": "full updated README.md content or empty string",
          "claude_md_content": "full updated CLAUDE.md content or empty string",
          "reasoning": "Brief explanation (2-3 sentences) of what changed and why documentation does/doesn't need updating"
        }
        USER_EOF
        
        SYSTEM_PROMPT=$(cat /tmp/system_prompt.txt)
        USER_PROMPT=$(cat /tmp/user_prompt.txt)
        
        # Call Claude API
        RESPONSE=$(curl -s -X POST "https://api.anthropic.com/v1/messages" \
          -H "x-api-key: $ANTHROPIC_API_KEY" \
          -H "anthropic-version: 2023-06-01" \
          -H "content-type: application/json" \
          --max-time 120 \
          -d "$(jq -n \
            --arg system "$SYSTEM_PROMPT" \
            --arg user "$USER_PROMPT" \
            '{
              "model": "claude-sonnet-4-20250514",
              "max_tokens": 8000,
              "temperature": 0.2,
              "system": $system,
              "messages": [{"role": "user", "content": $user}]
            }')")
        
        # Check for errors
        ERROR=$(echo "$RESPONSE" | jq -r '.error.message // empty')
        if [ -n "$ERROR" ]; then
          echo "Claude API error: $ERROR"
          echo "success=false" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Error" >> $GITHUB_STEP_SUMMARY
          echo "Claude API error: $ERROR" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        
        # Extract Claude's decision
        DECISION=$(echo "$RESPONSE" | jq -r '.content[0].text')
        echo "$DECISION" > /tmp/decision.json
        
        # Validate JSON
        if ! jq empty /tmp/decision.json 2>/dev/null; then
          echo "Invalid JSON response from Claude"
          echo "Response: $DECISION"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        # Parse decision
        UPDATE_README=$(jq -r '.update_readme' /tmp/decision.json)
        UPDATE_CLAUDE_MD=$(jq -r '.update_claude_md' /tmp/decision.json)
        REASONING=$(jq -r '.reasoning' /tmp/decision.json)
        
        echo "success=true" >> $GITHUB_OUTPUT
        echo "update_readme=$UPDATE_README" >> $GITHUB_OUTPUT
        echo "update_claude_md=$UPDATE_CLAUDE_MD" >> $GITHUB_OUTPUT
        echo "reasoning<<EOF" >> $GITHUB_OUTPUT
        echo "$REASONING" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Claude AI Analysis" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Update README.md:** $UPDATE_README" >> $GITHUB_STEP_SUMMARY
        echo "**Update CLAUDE.md:** $UPDATE_CLAUDE_MD" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Reasoning:** $REASONING" >> $GITHUB_STEP_SUMMARY

    - name: Create documentation PR
      id: create-pr
      if: steps.analyze.outputs.success == 'true' && (steps.analyze.outputs.update_readme == 'true' || steps.analyze.outputs.update_claude_md == 'true')
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
        REPOSITORY: ${{ inputs.repository }}
        ORIGINAL_PR_URL: ${{ steps.setup.outputs.pr_url }}
        UPDATE_README: ${{ steps.analyze.outputs.update_readme }}
        UPDATE_CLAUDE_MD: ${{ steps.analyze.outputs.update_claude_md }}
      run: |
        set -e
        
        echo "Creating documentation update PR..."
        
        BRANCH="docs/docsync-$(date +%Y%m%d-%H%M%S)"
        git checkout -b "$BRANCH"
        
        UPDATED_FILES=""
        
        if [ "$UPDATE_README" = "true" ]; then
          README_CONTENT=$(jq -r '.readme_content' /tmp/decision.json)
          if [ -n "$README_CONTENT" ] && [ "$README_CONTENT" != "null" ] && [ "$README_CONTENT" != "" ]; then
            printf '%s\n' "$README_CONTENT" > README.md
            git add README.md
            UPDATED_FILES="README.md"
            echo "README.md updated"
          fi
        fi
        
        if [ "$UPDATE_CLAUDE_MD" = "true" ]; then
          CLAUDE_CONTENT=$(jq -r '.claude_md_content' /tmp/decision.json)
          if [ -n "$CLAUDE_CONTENT" ] && [ "$CLAUDE_CONTENT" != "null" ] && [ "$CLAUDE_CONTENT" != "" ]; then
            printf '%s\n' "$CLAUDE_CONTENT" > CLAUDE.md
            git add CLAUDE.md
            if [ -n "$UPDATED_FILES" ]; then
              UPDATED_FILES="$UPDATED_FILES, CLAUDE.md"
            else
              UPDATED_FILES="CLAUDE.md"
            fi
            echo "CLAUDE.md updated"
          fi
        fi
        
        if ! git diff --cached --quiet; then
          REASONING=$(jq -r '.reasoning' /tmp/decision.json)
          
          git commit -m "docs: Automated documentation sync

        Updated: $UPDATED_FILES

        Triggered by: $COMMIT_SHA
        Reasoning: $REASONING"
          
          git push origin "$BRANCH"
          
          PR_BODY=$(cat << PRBODY_EOF
        ## Automated Documentation Update

        This PR was automatically generated by **DocSync AI** to keep documentation in sync with code changes.

        ### Files Updated
        $(echo "$UPDATED_FILES" | tr ',' '\n' | sed 's/^/- /')

        ### Why This Update?
        $REASONING

        ### Triggered By
        - **Commit:** \`$COMMIT_SHA\`
        - **Original PR:** $ORIGINAL_PR_URL

        ---
        *Generated by DocSync AI | Powered by Claude*
        PRBODY_EOF
        )

          PR_URL=$(gh pr create \
            --title "docs: Automated documentation update" \
            --body "$PR_BODY" \
            --base "$BASE_BRANCH" \
            --head "$BRANCH")
          
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          
          echo "pr_created=true" >> $GITHUB_OUTPUT
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "files_updated=$UPDATED_FILES" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Documentation PR Created" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**PR:** $PR_URL" >> $GITHUB_STEP_SUMMARY
          echo "**Files:** $UPDATED_FILES" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
        else
          echo "No actual changes detected after applying updates"
          echo "pr_created=false" >> $GITHUB_OUTPUT
          echo "files_updated=" >> $GITHUB_OUTPUT
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### No Changes" >> $GITHUB_STEP_SUMMARY
          echo "Documentation content matches existing files." >> $GITHUB_STEP_SUMMARY
        fi

    - name: Send Slack notification
      if: steps.create-pr.outputs.pr_created == 'true' && inputs.slack_webhook_url != ''
      shell: bash
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_USERS: ${{ inputs.slack_users_to_tag }}
        REPOSITORY: ${{ inputs.repository }}
        PR_URL: ${{ steps.create-pr.outputs.pr_url }}
        FILES_UPDATED: ${{ steps.create-pr.outputs.files_updated }}
        REASONING: ${{ steps.analyze.outputs.reasoning }}
      run: |
        USER_MENTIONS=""
        if [ -n "$SLACK_USERS" ]; then
          USER_MENTIONS=$(echo "$SLACK_USERS" | tr ',' '\n' | sed 's/^/<@/' | sed 's/$/>/' | tr '\n' ' ')
        fi
        
        SLACK_PAYLOAD=$(jq -n \
          --arg mentions "$USER_MENTIONS" \
          --arg repo "$REPOSITORY" \
          --arg pr_url "$PR_URL" \
          --arg files "$FILES_UPDATED" \
          --arg reasoning "$REASONING" \
          '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": (if $mentions != "" then $mentions + "\n" else "" end) + "*DocSync AI: Documentation Update Ready for Review*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Repository:* `\($repo)`\n*Files Updated:* \($files)\n\n<\($pr_url)|View Pull Request>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn", 
                  "text": "*Reasoning:*\n\($reasoning)"
                }
              },
              {
                "type": "context",
                "elements": [{"type": "mrkdwn", "text": "DocSync AI | Powered by Claude"}]
              }
            ]
          }')
        
        curl -s -X POST "$SLACK_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d "$SLACK_PAYLOAD" || echo "Slack notification failed"
        
        echo "Slack notification sent"

    - name: Set final status
      id: finalize
      if: always()
      shell: bash
      run: |
        if [ "${{ steps.create-pr.outputs.pr_created }}" = "true" ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Success - Documentation PR created" >> $GITHUB_STEP_SUMMARY
        elif [ "${{ steps.analyze.outputs.update_readme }}" = "false" ] && [ "${{ steps.analyze.outputs.update_claude_md }}" = "false" ]; then
          echo "status=skipped" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Skipped - No documentation updates needed" >> $GITHUB_STEP_SUMMARY
        elif [ "${{ steps.analyze.outputs.success }}" = "false" ]; then
          echo "status=error" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Error - Analysis failed" >> $GITHUB_STEP_SUMMARY
        else
          echo "status=skipped" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Skipped - No changes required" >> $GITHUB_STEP_SUMMARY
        fi
